String? mobileNumber;
String? email;
String? dOB;
int? nidNumber;
String? clearImageLocation;
String? imageLocation;
String? selfieLocation;
String? capturedPhotoPath;
String? name;
String? father;
String? mother;
String? presentAddress;
String? permanentAddress;
String nidAsString = "$nidNumber";
String? houseIdentifier;
String? streetAddress;
String? locality;
String? state;
String? postalCode;
String? country;
String? pin1;
String? pin2;
String uri = 'https://staging-gw.e-sign.com.bd:9100';
String uri2 = 'http://staging-gw.e-sign.com.bd:9100';
String? userid;
double? signatureX;
double? signatureY;
String? accessToken;
String? packageId;
String? algorithm;
int? keySize;
int? validityDaysInFuture = 1;
int? certificateSerialNumber;
